### ISSUE TITLE
GPIO34-39 are not directly usable as floating inputs

### ISSUE THREAD

**Issue by sapir** [esp-rs/esp32-hal#19]
```rust
dp.GPIO.split().gpio34
```
is a `GPIO34<Input<Floating>>`, but I tried reading from it without calling `into_floating_input()` and got 0. `into_floating_input()` fixed it. This may also apply to other pins as well; I ran into these because they don't have pullups/pulldowns, so I have to use them as floating pins anyway.

**Comment by arjanmels** [comment]
I will check the default assumed states to fix this.

**Comment by arjanmels** [comment]
Addressed by #36. Chosen to make all pin types Unknown by default: the state can change depending on the bootloader etc, so best not to trust on the defaults.

**Comment by arjanmels** [comment]
#36 is merged, should be ok to close now.
