### ISSUE TITLE
Blocking SPI Interface

### ISSUE THREAD

**Issue by fmckeogh** [esp-rs/esp32-hal#39]
ESP32 has four SPI peripherals, all of which can be used in master mode and two of which can be used in slave mode. `embedded-hal` defines a blocking interface which should be implemented and the use of DMA for an asynchronous interface needs to be planned and discussed.

**Comment by arjanmels** [comment]
Blocking interface implemented in #43. DMA still to be done (I don't plan to do this on short term).
