### ISSUE TITLE
Suspected typo / copy'n'paste bug in 'ram' macro

### ISSUE THREAD

**Issue by enrikb** [esp-rs/esp32-hal#50]
https://github.com/esp-rs/esp32-hal/blob/459bb29f661e7b6c3ef5cf99dc7335326276e880/procmacros/src/lib.rs#L69-L79

I was just reading over the code and spotted the above suspected typo. The second if condition is identical to the block above, however, the message suggests that it should check the 'initialization' parameters.

**Comment by MabezDev** [comment]
Good spot! Will Fix ASAP.
