### ISSUE TITLE
Linking error when enabling GPIO_INTR

### ISSUE THREAD

**Issue by schphil** [esp-rs/esp32-hal#64]
Hi there, attempting to enable the GPIO_INTR ( `esp32_hal::interrupt::enable(Interrupt::GPIO_INTR);` ) results in the following linking error. Thanks in advance.

<img width="1440" alt="Screenshot 2021-09-22 at 11 19 12" src="https://user-images.githubusercontent.com/44805897/134318302-d8b4e7b4-6c3f-45ac-985c-3c9f717e32e9.png">

**Comment by MabezDev** [comment]
Are you trying to use esp32-hal in a std application, like https://github.com/ivmarkov/rust-esp32-std-hello? Whilst I'd like this to work in the future, this is currently not a supported configuration.

I would say use the [idf-hal](https://github.com/esp-rs/esp-idf-hal/blob/master/src/gpio.rs) implementation but this does not have support for Interrupts just yet.

**Comment by schphil** [comment]
Thanks for the quick response. That is exactly what I am trying to do. Yes, I noticed that too which is why I tried the `esp32-hal` crate. I'll leave the interrupts for now. 

Should I close this one?
